### ISSUE TITLE
emuMMC

### ISSUE THREAD

**Issue by CRAWLER-V** [D3fau4/R3iNX#2]
Hello, How can configure hekate_ipl.ini for REINX emummc?
thanks.

**Comment by D3fau4** [comment]
you must configure emummc.ini, for this you can use hekate to create and configure or do it manually, you can follow this guide: https://switch.homebrew.guide/emummc/windows

make sure that in hekate the emummc is "enabled"

![60391771-f720bf80-9afe-11e9-9143-878cc70574b9](https://user-images.githubusercontent.com/19638408/77225963-70bc7a00-6b74-11ea-9a18-7d531473ef8b.png)

**Comment by CRAWLER-V** [comment]
> you must configure emummc.ini, for this you can use hekate to create and configure or do it manually, you can follow this guide: https://switch.homebrew.guide/emummc/windows
> 
> make sure that in hekate the emummc is "enabled"
> 
> ![60391771-f720bf80-9afe-11e9-9143-878cc70574b9](https://user-images.githubusercontent.com/19638408/77225963-70bc7a00-6b74-11ea-9a18-7d531473ef8b.png)

thanks for reply, yes is all set up like that, i've follow just that great guide.
but the guide dont create the .ini setting for booting up CFW on emuMMC.
the default hekate_ipl.ini for atmosphere is:

[Atmosphere FSS0 EmuMMC]
fss0=atmosphere/fusee-secondary.bin
kip1=atmosphere/kips/*
icon=bootloader/res/emu_boot.bmp
{}

i don't understand ho to configure this for reinx...
i tried:

[Stock]
fss0=ReiNX.bin
stock=1
emummc_force_disable=1

[emuMMC]
fss0=ReiNX.bin

but sems do not work.

**Comment by D3fau4** [comment]
???
and why are you doing that?

**Comment by CRAWLER-V** [comment]
becouse without hekate_ipl.ini configured, the launch page of the hekate is empty.

sems that rule for booting up emuMMC CFW for atmosphere was fss0=atmosphere/fusee-secondary.bin
I tried to find out what is the right rule to write in the ini for booting up emuMMC CFW for Reinx...  but i don't know the correct rule to write inside the ini (and hekate dont create one itselfe) :)

**Comment by D3fau4** [comment]
do you have a folder named emummc with a file emummc.ini in the SD?

**Comment by CRAWLER-V** [comment]
yes, this is what is write inside;

[emummc]
enabled=1
sector=0x3998000
path=emuMMC/RAW1
id=0x0000
nintendo_path=emuMMC/RAW1/Nintendo

**Comment by D3fau4** [comment]
Ok, well, simply launch the payload, you don't have to modify anything in hekate unless you want to launch the payload from hekate.

**Comment by CRAWLER-V** [comment]
AHH... allright. Thank you so much.
Now i see 9.2.0 ReiNX(2.5)|**E**
thank you,  thank you.
