### ISSUE TITLE
10.0.1 Support

### ISSUE THREAD

**Issue by loredanamilanesi2** [D3fau4/R3iNX#4]
I can't find anywhere to send you a message, sorry this is not the place for it, but does the ver 2.6 support 10.0.1 firmware?

**Comment by D3fau4** [comment]
yes

![image](https://user-images.githubusercontent.com/19638408/80516028-2902ec80-8983-11ea-876f-2b7243467194.png)

**Comment by loredanamilanesi2** [comment]
Thanks
